[package]
name = "quiche-hello"
version = "0.1.0"
edition = "2024"

[dependencies]
ring = "0.17.14"
tracing = "0.1"
tracing-subscriber = "0.3.0"
log = "0.4"
env_logger = "0.11.8"
quiche = "0.24.6"
mio = { version = "1.0.4", features = ["net", "os-poll"] }
url = { version = "2" }
octets = "0.3.0"
